name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write
  security-events: write
  packages: read

jobs:
  ci-checks:
    name: CI Checks
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release-please:
    name: Release Please
    needs: ci-checks
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Mint App token
        id: app
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Release Please
        uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ steps.app.outputs.token }}

  build-provisioner:
    name: Build Provisioner Artifact
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/build-provisioner.yml
    secrets: inherit
    with:
      version: ${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
      tag_name: ${{ needs.release-please.outputs.tag_name }}

  validate:
    name: Validate
    needs: build-provisioner
    uses: ./.github/workflows/validate.yml
